      logical msg_reg, msg_net, msg_rep_cs, msg_tght_cs, 
     &     msg_warn_edge, msg_err, msg_log, msg_solprt,
     &     msg_lamprt, msg_ranprt, msg_nonlin, msg_multstart,
     &     msg_wrt_sumdat
 
      common /msgc/ msg_reg, msg_net, msg_rep_cs, msg_tght_cs,
     &     msg_warn_edge, msg_err, msg_log,
     &     msg_solprt, msg_lamprt, msg_ranprt,
     &     msg_nonlin, msg_multstart, msg_wrt_sumdat
